[build-system]
    requires = ["hatchling"]
    build-backend = "hatchling.build"

[project]
    name = "irispie"
    version = "0.36.0"
    authors = [
      { name="Jaromir Benes", email="jaromir.benes@gmail.com" },
    ]
    description = "Macroeconomic modeling package"
    readme = "README.md"
    requires-python = ">=3.11"
    classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ]
    keywords = [
        "macroeconomics",
        "economics",
        "modeling",
        "simulation",
        "forecasting",
        "dsge",
    ]
    dependencies = [
        "numpy >= 1.25",
        "scipy >= 1.11",
        "plotly >= 5.15",
        "parsimonious >= 0.10",
        "prettytable >= 3.9",
        "pandas >= 2.1.2",
        "dill >= 0.3.7",
        "requests >= 2.31.0",
        "wlogging >= 0.1.2",
    ]

[project.urls]
    "Homepage" = "https://github.com/iris-solutions-team/irispie"
    "Bug Tracker" = "https://github.com/iris-solutions-team/irispie/issues"

